DROP TABLE INSTRUIR;
DROP TABLE ACESSA;
DROP TABLE PLANO_ESTUDANTE;
DROP TABLE MONITOR;
DROP TABLE ESTUDANTE;
DROP TABLE PLANO;
DROP TABLE CURSO;
DROP TABLE PROFESSOR;
DROP TABLE TELEFONES;
DROP TABLE ENDERECO;
DROP TABLE PESSOA;
DROP SEQUENCE SEQ_CURSO_ID;
DROP SEQUENCE SEQ_PLANO_ID;

CREATE TABLE PESSOA(
	CPF VARCHAR2(11) NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CONSTRAINT PESSOA PRIMARY KEY (CPF)
);

CREATE INDEX IDX_PESSOA
ON PESSOA(NOME);

CREATE TABLE ENDERECO(
	CPF_PESSOA VARCHAR2(11) NOT NULL,
	CEP VARCHAR2(8) NOT NULL,
	RUA VARCHAR2(50) NOT NULL,
	NUMERO NUMBER NOT NULL,
	CIDADE VARCHAR2(50) NOT NULL,
	ESTADO VARCHAR2(50) NOT NULL,
	CONSTRAINT ENDERECO_PK PRIMARY KEY (CPF_PESSOA, CEP),
	CONSTRAINT ENDERECO_CPF_FK FOREIGN KEY (CPF_PESSOA) REFERENCES PESSOA (CPF)
);

CREATE TABLE TELEFONES(
	CPF_PESSOA VARCHAR2(11),
	NUM_TELEFONE VARCHAR2(50),
	CONSTRAINT TELEFONES_PK PRIMARY KEY (CPF_PESSOA, NUM_TELEFONE),
	CONSTRAINT TELEFONES_CPF_FK FOREIGN KEY (CPF_PESSOA) REFERENCES PESSOA (CPF)
	
);

CREATE TABLE PROFESSOR(
	CPF_PROFESSOR VARCHAR2(11),
	CODIGO_ID NUMBER NOT NULL UNIQUE,
	CARGO VARCHAR2(50),
	SALARIO NUMBER(8,2),
	CPF_SUPERVISOR NUMBER NOT NULL,
	CONSTRAINT PROFESSOR_PK PRIMARY KEY (CPF_PROFESSOR),
	CONSTRAINT CPF_PROFESSOR_FK FOREIGN KEY (CPF_PROFESSOR) REFERENCES PESSOA (CPF)
);

CREATE TABLE CURSO(
	CURSO_ID NUMBER,
	NOME VARCHAR2(50) NOT NULL,
	CONSTRAINT CURSO_PK PRIMARY KEY (CURSO_ID)
);

CREATE SEQUENCE SEQ_CURSO_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE TABLE PLANO(
	PLANO_ID NUMBER,
	MENSALIDADE NUMBER CHECK (MENSALIDADE >= 100),
	CONSTRAINT PLANO_PK PRIMARY KEY (PLANO_ID)
);

CREATE SEQUENCE SEQ_PLANO_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE TABLE ESTUDANTE(
	CPF_ESTUDANTE VARCHAR2(11),
	CODIGO_ID NUMBER NOT NULL UNIQUE,
	COD_PLANO NUMBER NOT NULL,
	CONSTRAINT ESTUDANTE_PK PRIMARY KEY (CPF_ESTUDANTE),
	CONSTRAINT CPF_ESTUDANTE_FK FOREIGN KEY (CPF_ESTUDANTE) REFERENCES PESSOA (CPF),
	CONSTRAINT COD_PLANO_FK FOREIGN KEY (COD_PLANO) REFERENCES PLANO (PLANO_ID)
);

CREATE TABLE MONITOR(
	CPF_PROFESSOR VARCHAR2(11),
	MONITOR_ID NUMBER UNIQUE,
	NOME VARCHAR2(50),
	SALARIO NUMBER(6,2),
	CARGA_HORARIA NUMBER CHECK (CARGA_HORARIA >= 15),
	CONSTRAINT MONITOR_PK PRIMARY KEY (CPF_PROFESSOR, MONITOR_ID),
	CONSTRAINT CPF_MONITOR_FK FOREIGN KEY (CPF_PROFESSOR) REFERENCES PROFESSOR (CPF_PROFESSOR)
);

CREATE TABLE PLANO_ESTUDANTE(
	CPF_ESTUDANTE VARCHAR2(11),
	COD_PLANO NUMBER,
	CONSTRAINT PLANO_ESTUDANTE_PK PRIMARY KEY (CPF_ESTUDANTE, COD_PLANO),
	CONSTRAINT COD_PLANO_ESTUDANTE_FK FOREIGN KEY (COD_PLANO) REFERENCES PLANO (PLANO_ID)
);

ALTER TABLE PLANO_ESTUDANTE ADD DATA_INICIO DATE NOT NULL;
ALTER TABLE PLANO_ESTUDANTE ADD DATA_FIM DATE NOT NULL;

CREATE TABLE ACESSA(
	CPF_ESTUDANTE VARCHAR2(11),
	COD_PLANO NUMBER,
	COD_CURSO NUMBER,
	CONSTRAINT ACESSA_PK PRIMARY KEY (CPF_ESTUDANTE, COD_PLANO, COD_CURSO),
	CONSTRAINT ACESSA_CPF_ESTUDANTE_FK FOREIGN KEY (CPF_ESTUDANTE) REFERENCES PESSOA (CPF),
	CONSTRAINT ACESSA_COD_PLANO_FK FOREIGN KEY (COD_PLANO) REFERENCES PLANO (PLANO_ID),
	CONSTRAINT ACESSA_COD_CURSO_FK FOREIGN KEY (COD_PLANO) REFERENCES CURSO (CURSO_ID)
);

CREATE TABLE INSTRUIR(
	CPF_ESTUDANTE VARCHAR2(11),
	CPF_PROFESSOR VARCHAR2(11),
	COD_CURSO NUMBER,
	CONSTRAINT INSTRUIR_PK PRIMARY KEY (CPF_ESTUDANTE, CPF_PROFESSOR, COD_CURSO)
);
