DECLARE 
	V_PROFESSOR	PROFESSOR%ROWTYPE;
BEGIN 	
  	WHILE V_PROFESSOR.CODIGO_ID < 10 LOOP
	  	SELECT *
		INTO V_PROFESSOR
		FROM PROFESSOR;
  		
		dbms_output.put_line('value of a: ' || V_PROFESSOR.CODIGO_ID);  
     	V_PROFESSOR.CODIGO_ID := V_PROFESSOR.CODIGO_ID + 1; 
     
   EXIT WHEN V_PROFESSOR.CODIGO_ID = 5; 
   END LOOP; 
END; 