DECLARE 
	V_MONITOR		MONITOR%ROWTYPE;
BEGIN
	SELECT *
	INTO V_MONITOR
	FROM MONITOR
	WHERE MONITOR_ID = 4;
	
	DBMS_OUTPUT.PUT_LINE('Monitor ID: ' || V_MONITOR.MONITOR_ID);
	DBMS_OUTPUT.PUT_LINE('Nome: ' || V_MONITOR.NOME);
	DBMS_OUTPUT.PUT_LINE('Salario: ' || V_MONITOR.SALARIO);
	DBMS_OUTPUT.PUT_LINE('Cpf Professor Chefe: ' || V_MONITOR.CPF_PROFESSOR);
	
	EXCEPTION
	WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('!!!Não há monitor com esse ID!!!');
END;