DROP TABLE TB_PROFESSOR;
/
DROP TABLE TB_ESTUDANTE;
/
DROP TABLE TB_CURSO;
/
DROP TABLE TB_INSTRUI;
/
DROP TYPE TP_ENDERECO FORCE;
/
DROP TYPE TP_TELEFONE FORCE;
/
DROP TYPE VA_FONES FORCE;
/
DROP TYPE TP_PESSOA FORCE;
/
DROP TYPE TP_PROFESSOR FORCE;
/
DROP TYPE TP_MONITOR FORCE;
/
DROP TYPE TP_ESTUDANTE FORCE;
/
DROP TYPE TP_CURSO FORCE;
/
DROP TYPE TP_INSTRUI FORCE;
/

CREATE OR REPLACE TYPE TP_ENDERECO AS OBJECT(
    RUA VARCHAR2(50),
    NUMERO NUMBER,
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(50),
    CEP VARCHAR2(8),
    CONSTRUCTOR FUNCTION TP_ENDERECO(ruaEnd VARCHAR2, numEnd NUMBER, cidadeEnd VARCHAR2, estadoEnd VARCHAR2) RETURN SELF AS RESULT
);
/

-- **** Cria telefone e altera seus atributos ****
CREATE OR REPLACE TYPE TP_TELEFONE AS OBJECT(
    NUMERO VARCHAR2(8)
)NOT FINAL;
/
ALTER TYPE TP_TELEFONE ADD ATTRIBUTE(DDD VARCHAR2(2)) CASCADE;
/
ALTER TYPE TP_TELEFONE DROP ATTRIBUTE NUMERO CASCADE;
/
ALTER TYPE TP_TELEFONE ADD ATTRIBUTE(NUMERO VARCHAR2(9)) CASCADE;
/
ALTER TYPE TP_TELEFONE FINAL INVALIDATE;
/

CREATE OR REPLACE TYPE VA_FONES AS VARRAY(4) OF TP_TELEFONE;
/

CREATE OR REPLACE TYPE TP_PESSOA AS OBJECT(
    CPF VARCHAR2(11),
    NOME VARCHAR2(50),
    DATA_NASCIMENTO DATE,
    TELEFONES VA_FONES,
    ENDEREÇO TP_ENDERECO,
    FINAL MAP MEMBER FUNCTION getCPF RETURN NUMBER,
    MEMBER FUNCTION getNome RETURN VARCHAR2
)NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE TP_MONITOR AS OBJECT(
    MONITOR_ID NUMBER,
    NOME VARCHAR2(50),
    SALARIO NUMBER(6,2),
    CARGA_HORARIA NUMBER(2),
    MEMBER PROCEDURE salarioCarga(ids NUMBER, nome VARCHAR2)
);
/
CREATE OR REPLACE TYPE TP_NT_AUXILIARES AS TABLE OF TP_MONITOR;
/

CREATE OR REPLACE TYPE TP_PROFESSOR UNDER TP_PESSOA(
    CARGO VARCHAR2(50),
    SALARIO NUMBER(8,2),
    PROFESSOR_ID NUMBER(1),
    SUPERVISOR REF TP_PROFESSOR,
    MONITOR TP_NT_AUXILIARES,
    OVERRIDING MEMBER FUNCTION getNome RETURN VARCHAR2,
    MEMBER PROCEDURE aumentarSalario(aumento NUMBER)
);
/

CREATE OR REPLACE TYPE TP_ESTUDANTE UNDER TP_PESSOA(
    MENSALIDADE NUMBER(5,2),
    BOLSA NUMBER(5,2),
    MEMBER FUNCTION investimento RETURN NUMBER
);
/

CREATE OR REPLACE TYPE TP_CURSO AS OBJECT(
    CURSO_ID NUMBER,
    DURACAO NUMBER(3),
    NOME VARCHAR2(50),
    ORDER MEMBER FUNCTION maiorDuracao(d TP_CURSO) RETURN NUMBER
);
/

CREATE OR REPLACE TYPE TP_INSTRUI AS OBJECT(
    PROFESSOR REF TP_PROFESSOR,
    ESTUDANTE REF TP_ESTUDANTE,
    CURSO REF TP_CURSO
);
/
