CREATE TABLE TB_PROFESSOR OF TP_PROFESSOR (
    CPF PRIMARY KEY,
    SUPERVISOR WITH ROWID REFERENCES TB_PROFESSOR
)NESTED TABLE MONITOR STORE AS TB_LISTA_MONITORES;
/

CREATE TABLE TB_ESTUDANTE OF TP_ESTUDANTE (
    CPF PRIMARY KEY
);
/

CREATE TABLE TB_CURSO OF TP_CURSO (
    CURSO_ID PRIMARY KEY
);
/

CREATE TABLE TB_INSTRUI OF TP_INSTRUI (
    PROFESSOR SCOPE IS TB_PROFESSOR,
    ESTUDANTE SCOPE IS TB_ESTUDANTE,
    CURSO SCOPE IS TB_CURSO
);
/