-- DEREF
SELECT DEREF(P.SUPERVISOR) FROM TB_PROFESSOR P;

SELECT DEREF(P.SUPERVISOR).nome FROM TB_PROFESSOR P
WHERE P.SUPERVISOR IS NOT DANGLING;

SELECT DEREF(I.PROFESSOR).nome FROM TB_INSTRUI I;

SELECT DEREF(P.SUPERVISOR).nome as GERENTE, P.NOME AS GERENCIADO 
FROM TB_PROFESSOR P;

--VALUE
SELECT VALUE(P) AS LISTA_PROFESSORES FROM TB_PROFESSOR P;
/

DECLARE
ESTUDANTE TP_ESTUDANTE;
INVESTIMENTO NUMBER;
BEGIN
    SELECT VALUE(E) INTO ESTUDANTE FROM TB_ESTUDANTE E WHERE E.MENSALIDADE = 500.00;
    INVESTIMENTO := ESTUDANTE.INVESTIMENTO();
    dbms_output.put_line(INVESTIMENTO);
END;
/

-- Consulta Varray
SELECT * FROM TABLE
(SELECT P.TELEFONES FROM TB_PROFESSOR P WHERE CPF = '11999999999');

-- Consulta Nested
SELECT * FROM TABLE
(SELECT P.MONITOR FROM TB_PROFESSOR P WHERE CPF = '10999999999');